# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 320a27caf600a8c609f06447d21318b084e64fe550dc5edbad155315f907f0d3dfe66343d037af9f0c10d17e5b406212a032d5e017dfdb188e838ca59bd72230

test:
  secret_key_base: 4d8582871c8580e69c02717b3336c9e9cc3afc11cbc8cceb8b17904086f450cb093ef60a29dbf0020f40d2852fd91caae27d65e34a7935a3459ba3991501bcad

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
